### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by haryu703**

### CODE REVIEW

**Comment by cgcardona** [comment]
Unfortunately that typo is needed as it's in the [WH codebase](https://github.com/copernet/wormhole)

screen shot 2018-10-07 at 8 40 21 am

**Comment by haryu703** [comment]
I am sorry I did not know it was intentional.

wormholed side seems to have been fixed already.
https://github.com/copernet/wormhole/commit/306aa63ac7e225bb8f8ab4b503d87f9deec04052#diff-ff504005a9e300bd1b8e820f9156d99aL18
I would like you to check again when you can up the version of wormholed.

**Comment by cgcardona** [comment]
BTW wormholerest has been merged in to rest.bitcoin.com. It will be live there early next week. This repo is deprecated.

When we deploy wormholerest to rest.bitcoin.com this PR will be fixed. I just confirmed that in our staging env this typo is fixed.

**Comment by haryu703** [comment]
I see. Thank you for your explanation.
I will close this pull request.

**Comment by cgcardona** [comment]
Please  recreate this PR against the stage branch of rest.bitcoin. https://github.com/Bitcoin-com/rest.bitcoin.com/tree/stage

Thanks

**Pull request closed without merging**
